export enum OfferTypeEnum {
    ONBOARDING_AMOUNT_OFFER = 'ONBOARDING_AMOUNT_OFFER',
    DISCOUNTED_ITEM_OFFER = 'DISCOUNTED_ITEM_OFFER',
    CASHBACK_OFFER = 'CASHBACK_OFFER',
    MINIMUM_RECHARGE_OFFER = 'MINIMUM_RECHARGE_OFFER',
    ORDER_DISCOUNT_OFFER = 'ORDER_DISCOUNT_OFFER',
}